let PacketID = ck.PacketID;

// region Login
PacketID.HANDSHAKE = 0;
PacketID.LOGIN = 1;
PacketID.LOGIN_INFO = 1001;
PacketID.RELOGIN = 1704;
PacketID.LOGOUT = 1701;
// endregion

// region Cheat
PacketID.CHEAT = 1706;
// endregion

// region Profile
PacketID.PROFILE_INFO = 1002;
PacketID.USER_AVATAR = 1003;
PacketID.LEVEL_UP = 1007;
PacketID.FEATURES_INFO = 1008;
PacketID.RATING_OPEN = 4071;
PacketID.RATING = 4072;
PacketID.INVENTORY_INFO = 1004;
PacketID.ITEMS_INFO = 1009;
PacketID.PROFILE_USER_INFO = 1006;
PacketID.ACTIVATE_SKIN = 1010;
PacketID.DEACTIVATE_SKIN = 1011;
PacketID.REFUND_BAN_INFO = 1012;
PacketID.CLAIM_COMPENSATION = 1013;
PacketID.ACCUMULATION_INFO = 1014;
PacketID.USE_BOOSTER_V2 = 4202;
PacketID.EXP_MILESTONE_INFO = 1241;
PacketID.ENTER_ERROR = 4203;
// endregion

// region System
PacketID.SYSTEM_SERVER_TIME = 1702;
PacketID.SYSTEM_GAME_FEATURES = 1703;
PacketID.SYSTEM_BROADCAST = 1705;
PacketID.SYSTEM_RECOMMEND_UPDATE = 1707;
PacketID.SYSTEM_LOG = 1708;
PacketID.SYSTEM_SURVEY_INFO = 4301;
PacketID.SYSTEM_SURVEY_ANSWER = 4302;
// endregion

// region Broadcast
PacketID.BROADCAST_INFO = 4091;
// endregion

// region Localize
PacketID.CHANGE_LANGUAGE = 1005;
// endregion

// region Tutorial
PacketID.TUTORIAL_FINISH = 4001;
// endregion

// region Payment
PacketID.PAYMENT_INFO = 1601;
PacketID.PAYMENT_BUY = 1602;
PacketID.PAYMENT_LAST_BUY_INFO = 1603;
PacketID.IAP_INFO = 1621;
PacketID.IAP_VERIFY = 1622;
PacketID.OFFER_INFO = 1634;
PacketID.OFFER_REMOVE = 1632;
PacketID.OFFER_AUTO_PAY = 1633;
PacketID.PAYMENT_EVENT_INFO = 3981;
PacketID.PAYMENT_SHOP_BUY = 3982;
PacketID.PAYMENT_EVENT_CHOOSE = 3983;
// endregion

// region Free
PacketID.FREE_COIN_INFO = 1101;
PacketID.TIME_REWARD_CLAIM = 1102;
PacketID.DAILY_REWARD_CLAIM = 1103;
PacketID.SUPPORT_COIN = 1104;
PacketID.COMEBACK_REWARD = 1105;
PacketID.GIFT_CODE_SUBMIT = 4050;
// endregion

// region Mailbox
PacketID.MAIL_LIST = 1130;
PacketID.MAIL_CLAIM = 1131;
PacketID.MAIL_UPDATE = 1132;
PacketID.MAIL_MESSAGE = 1133;
PacketID.NEWS_INFO = 1134;
PacketID.NEWS_ENTER = 1135;
// endregion

// region Quest
PacketID.QUEST_INFO = 1160;
PacketID.QUEST_UPDATE = 1162;
PacketID.QUEST_REFRESH = 1163;
PacketID.QUEST_CLAIM = 1161;
PacketID.QUEST_MILESTONE_CLAIM = 1164;
// endregion

// region Gameplay
PacketID.GAME_BET_CHANNEL_INFO = 1524;
PacketID.GAME_ENTER = 1502;
PacketID.GAME_LEAVE = 1504;
PacketID.GAME_PLAYER_ENTER = 1503;
PacketID.GAME_READY = 1505;
PacketID.GAME_START_ROUND = 1510;
PacketID.GAME_DEAL = 1511;
PacketID.GAME_PLACE_CARD = 1512;
PacketID.GAME_LAST_ROUND_COLLECT = 1517;
PacketID.GAME_END_GAME = 1508;
PacketID.GAME_REWARDS = 1509;
PacketID.GAME_CHAT = 1506;
PacketID.GAME_CHAT_TROPHY = 1567;
PacketID.GAME_STATUS = 1507;
PacketID.GAME_RECONNECT_INFO = 1520;
PacketID.GAME_RECONNECT = 1521;
PacketID.GAME_SUGGEST_PLAY = 1566;
PacketID.BIG_BET_INFO = 1522;
PacketID.BIG_BET_RESULT = 1523;
PacketID.PISTI_POINT_INFO = 1525;
// endregion

// region Skill
PacketID.SKILL_INFO = 1556;
PacketID.SKILL_ACTIVE = 1557;
PacketID.SKILL_UPDATE = 1558;
PacketID.SKILL_CARDS = 1559;
// endregion

// region Jackpot
PacketID.JACKPOT_INFO = 1541;
PacketID.JACKPOT_UPDATE = 1542;
PacketID.JACKPOT_WHEEL_INFO = 1544;
PacketID.JACKPOT_WHEEL_TURN = 1545;
// endregion

// region Friend
PacketID.FRIEND_LIST = 1201;
PacketID.FRIEND_INVITATION_LIST = 1202;
PacketID.FRIEND_INVITATION_REQUEST = 1203;
PacketID.FRIEND_INVITATION_ANSWER = 1204;
PacketID.FRIEND_REMOVE = 1205;
PacketID.FRIEND_SEARCH = 1006;
PacketID.FRIEND_SEND_GIFT = 1206;
PacketID.FRIEND_RECEIVE_GIFT = 1207;
PacketID.FRIEND_NOTIFY = 1208;
PacketID.FRIEND_INTERACT_ITEM_LIST = 1209;
// endregion

// region Interact
PacketID.GAME_SEND_ITEM = 1551;
PacketID.GAME_RECEIVE_ITEM = 1552;
PacketID.GAME_INTERACT_ITEM_INFO = 1501;
// endregion

// region Invite Friend
PacketID.INVITE_FRIEND_INFO = 1216;
PacketID.INVITE_FRIEND_SUBMIT = 1217;
PacketID.INVITE_FRIEND_UPDATE = 1218;
PacketID.INVITE_FRIEND_CLAIM = 1219;
// endregion

// region Share Image
PacketID.SHARE_IMAGE_INFO = 4054; // 4051 is for old client version, doesn't use it anymore
PacketID.SHARE_IMAGE_CLAIM = 4055; // 4052 is for old client version, doesn't use it anymore
PacketID.SHARE_IMAGE_EVENT_INFO = 4053;
// endregion

// region Ranking
PacketID.RANKING_INFO = 4081;
PacketID.RANKING_TABLE = 4082;
PacketID.RANKING_REWARD = 4083;
// endregion

// region League
PacketID.LEAGUE_INFO = 4141;
PacketID.LEAGUE_GROUP_INFO = 4142;
PacketID.LEAGUE_TABLE = 4143;
PacketID.LEAGUE_REWARD = 4144;
// endregion

// region Shop
PacketID.SHOP_INFO_OLD = 1226;
PacketID.SHOP_BUY = 1227;
PacketID.SHOP_INFO = 1228;
// endregion

// region Card Collection
PacketID.CARD_COLLECTION_INFO = 4101;
PacketID.CARD_COLLECTION_RESET_CARDSET = 4102;
PacketID.CARD_COLLECTION_ENTER = 4103;
PacketID.CARD_COLLECTION_USE_JOKER_CARD = 4104;
PacketID.CARD_COLLECTION_CLAIM_CARD_OLD = 4105; // For client version < 6
PacketID.CARD_COLLECTION_CLAIM_CARD = 4106; // For client version >= 6
// endregion

// region Trophy
PacketID.TROPHY_INFO = 4121;
PacketID.TROPHY_UPDATE = 4122;
PacketID.TROPHY_VIEW_NEW = 4123;
PacketID.TROPHY_SELECT = 4124;
PacketID.TROPHY_DESELECT = 4125;
PacketID.TROPHY_MILESTONE_INFO = 4126;
PacketID.TROPHY_MILESTONE_UPDATE = 4127;
PacketID.TROPHY_TOP_INFO = 4128;
// endregion

// region Minigames

// region [Minigame] Gourd Crab
PacketID.GOURD_CRAB_ENTER = 2011;
PacketID.GOURD_CRAB_BET = 2019;
PacketID.GOURD_CRAB_READY = 2015;
PacketID.GOURD_CRAB_RETRACT = 2013;
PacketID.GOURD_CRAB_CHAT = 2014;
PacketID.GOURD_CRAB_CHAT_TROPHY = 2021;
PacketID.GOURD_CRAB_GIFT = 2016;
PacketID.GOURD_CRAB_JOIN = 2018;
PacketID.GOURD_CRAB_RESULT = 2022;
PacketID.GOURD_CRAB_LEAVE = 2012;
PacketID.GOURD_CRAB_STATUS = 2017;
// endregion

// region [Minigame] Bingo
PacketID.BINGO_ENTER = 2031;
PacketID.BINGO_READY = 2032;
PacketID.BINGO_BET = 2033;
PacketID.BINGO_LEAVE = 2034;
PacketID.BINGO_CHAT = 2035;
PacketID.BINGO_CHAT_TROPHY = 2041;
PacketID.BINGO_GIFT = 2036;
PacketID.BINGO_JOIN = 2037;
PacketID.BINGO_RESULT = 2042;
PacketID.BINGO_STATUS = 2039;
PacketID.BINGO_TOKEN = 2040;
// endregion

// region [Minigame] Card Flip
PacketID.MINIGAME_05_CARDFLIP_ENTER      	= 2071;
PacketID.MINIGAME_05_CARDFLIP_STATE      	= 2072;
PacketID.MINIGAME_05_CARDFLIP_NOTIFY_JOIN   = 2073;
PacketID.MINIGAME_05_CARDFLIP_READY       	= 2074;
PacketID.MINIGAME_05_CARDFLIP_BET         	= 2075;
PacketID.MINIGAME_05_CARDFLIP_RESULT        = 2084;
PacketID.MINIGAME_05_CARDFLIP_CHAT        	= 2077;
PacketID.MINIGAME_05_CARDFLIP_CHAT_TROPHY   = 2083;
PacketID.MINIGAME_05_CARDFLIP_EQUIPMENTS  	= 2078;
PacketID.MINIGAME_05_CARDFLIP_LEAVE       	= 2079;
PacketID.MINIGAME_05_CARDFLIP_INTERACT_INFO = 2080;
PacketID.MINIGAME_05_CARDFLIP_INTERACT_ITEM_SENT = 2081;
PacketID.MINIGAME_05_CARDFLIP_INTERACT_ITEM_RECEIVED = 2082;
// endregion

// region [Minigame] Poker
PacketID.POKER_ENTER = 2091;
PacketID.POKER_BET = 2092;
PacketID.POKER_DRAW = 2093;
PacketID.POKER_RESULT = 2094;
PacketID.POKER_LEAVE = 2095;
// endregion

// region [Minigame] Slot Machine
PacketID.SLOT_THREE_ENTER = 2001;
PacketID.SLOT_THREE_TURN = 2002;
PacketID.SLOT_THREE_LEAVE = 2003;
PacketID.SLOT_THREE_JACKPOT_INFO = 2004;
// endregion

// endregion

// region Events

// region [Event] New Comer
PacketID.EVENT_01_NEW_COMER_INFO = 3001;
PacketID.EVENT_01_NEW_COMER_UPDATE = 3002;
PacketID.EVENT_01_NEW_COMER_CLAIM_ACTION = 3003;
PacketID.EVENT_01_NEW_COMER_CLAIM_MILESTONE = 3004;
// endregion

// region [Event] Build Up Pay
PacketID.BUILD_UP_PAY_INFO = 3071;
PacketID.BUILD_UP_PAY_CLAIM = 3072;
PacketID.BUILD_UP_PAY_UPDATE = 3073;
// endregion

// region [Event11] ContinuousPerchase
PacketID.CONTINUOUS_PURCHASE_INFO = 3191;
PacketID.CONTINUOUS_PURCHASE_CLAIM = 3192;
// endregion

// region [Event07] PlayToDonate
PacketID.PLAY_TO_DONATE_INFO = 3111;
PacketID.PLAY_TO_DONATE_CLAIM = 3112;
PacketID.PLAY_TO_DONATE_ACCUMULATE = 3113;
// endregion

// region [Event12] EXP PASS
PacketID.EXP_PASS_INFO = 3201;
PacketID.EXP_PASS_MILESTONE = 3202;
PacketID.EXP_PASS_CLAIM = 3203;
PacketID.EXP_PASS_RESET = 3204;
// endregion

PacketID.RESP_COMBO_ITEM_INFO = 4201;

// region [Event15] VanCat
PacketID.EVENT15_INFO = 3271;
PacketID.EVENT15_UPDATE = 3272;
PacketID.EVENT15_MILESTONE = 3273;
PacketID.EVENT15_CHOOSE_PAY = 3274;
PacketID.EVENT15_PAYMENT_SUCCESS = 3275;
// endregion

// region [Event] Happy Shark
PacketID.HAPPY_SHARK_INFO = 3014;
PacketID.HAPPY_SHARK_ENTER = 3011;
PacketID.HAPPY_SHARK_LEAVE = 3013;
PacketID.HAPPY_SHARK_TURN = 3012;
PacketID.HAPPY_SHARK_RESET = 3015;
PacketID.HAPPY_SHARK_CURRENT_ACCUMULATE = 3016;
PacketID.HAPPY_SHARK_UPDATE_TOKEN = 3017;
// endregion

// region [Event] Around The World
PacketID.AROUND_THE_WORLD_INFO = 3051;
PacketID.AROUND_THE_WORLD_DATA = 3052;
PacketID.AROUND_THE_WORLD_FLY = 3053;
PacketID.AROUND_THE_WORLD_RESET = 3054;
PacketID.AROUND_THE_WORLD_SELECT_REWARD = 3055;
// endregion

// region [Event] Dragon Knight
PacketID.DRAGON_KNIGHT_INFO = 3131;
PacketID.DRAGON_KNIGHT_CLAIM = 3132;
PacketID.DRAGON_KNIGHT_TOKEN = 3133;
// endregion

// region [Event] Dual Wheel
PacketID.DUAL_WHEEL_INFO = 3031;
PacketID.DUAL_WHEEL_ENTER = 3032;
PacketID.DUAL_WHEEL_SPIN = 3034;
PacketID.DUAL_WHEEL_LEAVE = 3033;
PacketID.DUAL_WHEEL_UPDATE = 3035;
PacketID.DUAL_WHEEL_SELECT = 3036;
// endregion

// region Event Collector
PacketID.EVENT_COLLECTOR_INFO = 3091;
PacketID.EVENT_COLLECTOR_EXCHANGE_REWARD = 3092;
PacketID.EVENT_COLLECTOR_REWARD = 3093;
PacketID.EVENT_COLLECTOR_GACHA_INFO = 3094;
PacketID.EVENT_COLLECTOR_GACHA_SPIN = 3095;
PacketID.EVENT_COLLECTOR_USER_INFO_NEEDED = 3096;
PacketID.EVENT_COLLECTOR_SUBMIT_USER_INFO = 3097;
PacketID.EVENT_COLLECTOR_VERIFY_USER_INFO = 3098;
// endregion

// region Pinball
PacketID.PINBALL_ENTER = 2101;
PacketID.PINBALL_TURN = 2102;
PacketID.PINBALL_LEAVE = 2103;
// endregion

// endregion